# Generated by Django 6.0.2 on 2026-04-06 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JogoBGG',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('yearpublished', models.IntegerField(blank=True, default=0, null=True)),
                ('is_expansion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Jogo BGG',
                'verbose_name_plural': 'Jogos BGG',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criadoPor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('pontos', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criadoPor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classificacoes', to='apiBoardGameStats.jogador')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('anoLancamento', models.IntegerField(blank=True, null=True)),
                ('bggId', models.IntegerField(blank=True, null=True)),
                ('isExpansao', models.BooleanField(default=False)),
                ('criadoPor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criadoPor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPartida', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criadoPor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('jogadores', models.ManyToManyField(related_name='partidas', through='apiBoardGameStats.Classificacao', to='apiBoardGameStats.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='apiBoardGameStats.jogo')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='apiBoardGameStats.local')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.AddField(
            model_name='classificacao',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='apiBoardGameStats.partida'),
        ),
        migrations.CreateModel(
            name='UUIDJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuids', to='apiBoardGameStats.jogador')),
            ],
        ),
    ]
