# Generated by Django 6.0.2 on 2026-04-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBoardGameStats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='jogo',
        ),
        migrations.CreateModel(
            name='JogosPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_jogo', to='apiBoardGameStats.jogo')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_partida', to='apiBoardGameStats.partida')),
            ],
            options={
                'verbose_name': 'Jogo da Partida',
                'verbose_name_plural': 'Jogos da Partida',
            },
        ),
        migrations.AddField(
            model_name='partida',
            name='jogos',
            field=models.ManyToManyField(related_name='partidas', through='apiBoardGameStats.JogosPartida', to='apiBoardGameStats.jogo'),
        ),
    ]
