# Generated by Django 6.0.2 on 2026-04-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiBoardGameStats', '0002_remove_partida_jogo_jogospartida_partida_jogos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UUIDJogador',
        ),
    ]
